print('A velocity calculator in python')
a = int(input("Enter the acceleration"))
u = int(input("Enter the initial velocity"))
t = int(input("Enter the time"))
v = int(u) + int(a) * int(t)
print("The velocity is", v)
